-- Bảng question
CREATE TABLE review_questions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    is_deleted      BOOLEAN                                 NOT NULL,

    content         VARCHAR(255)                            NOT NULL,
    weight          INTEGER                                 NOT NULL, -- độ quan trọng của câu hỏi
    display_order   INTEGER, -- thứ tự hiển thị

    is_active       BOOLEAN DEFAULT TRUE
);

-- Bảng options đáp án
CREATE TABLE review_options (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    is_deleted      BOOLEAN                                 NOT NULL,

    question_id     BIGINT                                  NOT NULL,
    content         VARCHAR(255)                            NOT NULL,

    star_value      INTEGER                                 NOT NULL, -- 1 -> 5 sao

    display_order   INTEGER,

    CONSTRAINT fk_ro_question FOREIGN KEY (question_id) REFERENCES review_questions(id) ON DELETE CASCADE
);

-- Bảng review chính
CREATE TABLE recipe_reviews (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    is_deleted      BOOLEAN                                 NOT NULL,

    recipe_id       BIGINT                                  NOT NULL,
    user_id         BIGINT                                  NOT NULL,

    rating          DOUBLE PRECISION                        NOT NULL, -- kết quả cuối (VD: 4.5)
    total_weight    INTEGER, -- tổng weight đã dùng (optional debug)

    review_text     VARCHAR, -- optional text

    CONSTRAINT fk_rr_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,

    CONSTRAINT unique_user_recipe_review UNIQUE (user_id, recipe_id)
);

-- Bảng câu trả lời user
CREATE TABLE review_answers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    is_deleted      BOOLEAN                                 NOT NULL,

    review_id       BIGINT                                  NOT NULL,
    question_id     BIGINT                                  NOT NULL,
    option_id       BIGINT                                  NOT NULL,

    star_value      INTEGER                                 NOT NULL, -- snapshot để tránh lệch data
    weight          INTEGER                                 NOT NULL, -- snapshot weight tại thời điểm review

    CONSTRAINT fk_ra_review FOREIGN KEY (review_id) REFERENCES recipe_reviews(id) ON DELETE CASCADE,
    CONSTRAINT fk_ra_question FOREIGN KEY (question_id) REFERENCES review_questions(id) ON DELETE CASCADE,
    CONSTRAINT fk_ra_option FOREIGN KEY (option_id) REFERENCES review_options(id) ON DELETE CASCADE
);

CREATE INDEX idx_review_recipe ON recipe_reviews(recipe_id);
CREATE INDEX idx_review_user ON recipe_reviews(user_id);
CREATE INDEX idx_answer_review ON review_answers(review_id);