-- Bảng question
CREATE TABLE review_questions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    is_deleted      BOOLEAN                                 NOT NULL,

    content         VARCHAR(255)                            NOT NULL,
    weight          INTEGER                                 NOT NULL, -- độ quan trọng của câu hỏi

    is_active       BOOLEAN DEFAULT TRUE
);

-- Bảng options đáp án
CREATE TABLE review_options (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    is_deleted      BOOLEAN                                 NOT NULL,

    question_id     BIGINT                                  NOT NULL,
    content         VARCHAR(255)                            NOT NULL,

    star_value      INTEGER                                 NOT NULL, -- 1 -> 5 sao

    CONSTRAINT fk_ro_question FOREIGN KEY (question_id) REFERENCES review_questions(id) ON DELETE CASCADE
);

-- Bảng review chính
CREATE TABLE recipe_reviews (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    is_deleted      BOOLEAN                                 NOT NULL,

    recipe_id       BIGINT                                  NOT NULL,
    user_id         BIGINT                                  NOT NULL,

    rating          DOUBLE PRECISION                        NOT NULL, -- kết quả cuối (VD: 4.5)
    total_weight    INTEGER, -- tổng weight đã dùng

    review_text     VARCHAR, -- optional text

    CONSTRAINT fk_rr_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,

    CONSTRAINT unique_user_recipe_review UNIQUE (user_id, recipe_id)
);

-- Bảng câu trả lời user
CREATE TABLE review_answers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    is_deleted      BOOLEAN                                 NOT NULL,

    review_id       BIGINT                                  NOT NULL,
    question_id     BIGINT                                  NOT NULL,
    option_id       BIGINT                                  NOT NULL,

    star_value      INTEGER                                 NOT NULL, -- snapshot để tránh lệch data
    weight          INTEGER                                 NOT NULL, -- snapshot weight tại thời điểm review

    CONSTRAINT fk_ra_review FOREIGN KEY (review_id) REFERENCES recipe_reviews(id) ON DELETE CASCADE,
    CONSTRAINT fk_ra_question FOREIGN KEY (question_id) REFERENCES review_questions(id) ON DELETE CASCADE,
    CONSTRAINT fk_ra_option FOREIGN KEY (option_id) REFERENCES review_options(id) ON DELETE CASCADE
);

CREATE INDEX idx_review_recipe ON recipe_reviews(recipe_id);
CREATE INDEX idx_review_user ON recipe_reviews(user_id);
CREATE INDEX idx_answer_review ON review_answers(review_id);


INSERT INTO review_questions (id, created_at, updated_at, created_by, updated_by, is_deleted, content, weight, is_active)
VALUES
    (1, NOW(), NOW(), 'system', 'system', FALSE, 'Món ăn có ngon không?', 3,  TRUE),
    (2, NOW(), NOW(), 'system', 'system', FALSE, 'Công thức có dễ làm không?', 2,  TRUE),
    (3, NOW(), NOW(), 'system', 'system', FALSE, 'Thành phẩm có giống mô tả không?', 2,  TRUE),
    (4, NOW(), NOW(), 'system', 'system', FALSE, 'Bạn có muốn nấu lại món này không?', 1,  TRUE);

INSERT INTO review_options (created_at, updated_at, created_by, updated_by, is_deleted, question_id, content, star_value)
VALUES
    (NOW(), NOW(), 'system', 'system', FALSE, 1, 'Rất ngon', 5),
    (NOW(), NOW(), 'system', 'system', FALSE, 1, 'Bình thường', 3),
    (NOW(), NOW(), 'system', 'system', FALSE, 1, 'Không ngon', 1), -- Q1
    (NOW(), NOW(), 'system', 'system', FALSE, 2, 'Rất dễ làm', 5),
    (NOW(), NOW(), 'system', 'system', FALSE, 2, 'Bình thường', 3),
    (NOW(), NOW(), 'system', 'system', FALSE, 2, 'Khó làm', 1), -- Q2
    (NOW(), NOW(), 'system', 'system', FALSE, 3, 'Rất giống mô tả', 5),
    (NOW(), NOW(), 'system', 'system', FALSE, 3, 'Hơi khác một chút', 3),
    (NOW(), NOW(), 'system', 'system', FALSE, 3, 'Không giống', 1), -- Q3
    (NOW(), NOW(), 'system', 'system', FALSE, 4, 'Có, chắc chắn sẽ nấu lại', 5),
    (NOW(), NOW(), 'system', 'system', FALSE, 4, 'Không, sẽ không nấu lại', 1); -- Q4
