CREATE TABLE cooking_sessions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    updated_by  VARCHAR(255)                            NOT NULL,
    is_deleted  BOOLEAN                                 NOT NULL,

    user_id         BIGINT NOT NULL,
    recipe_id       BIGINT NOT NULL,

    status          VARCHAR(20) NOT NULL, -- IN_PROGRESS, COMPLETED, ABANDONED
    current_step    INTEGER DEFAULT 1, -- step hiện tại

    started_at      TIMESTAMP WITHOUT TIME ZONE,
    completed_at    TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT fk_cs_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE
);

CREATE TABLE cooking_session_steps (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    updated_by  VARCHAR(255)                            NOT NULL,
    is_deleted  BOOLEAN                                 NOT NULL,

    cooking_session_id  BIGINT NOT NULL,
    recipe_step_id      BIGINT NOT NULL,

    step_number         INTEGER NOT NULL,

    status              VARCHAR(20) NOT NULL, -- PENDING, IN_PROGRESS, DONE

    started_at          TIMESTAMP,
    completed_at        TIMESTAMP,

    CONSTRAINT fk_css_session FOREIGN KEY (cooking_session_id) REFERENCES cooking_sessions(id) ON DELETE CASCADE,

    CONSTRAINT fk_css_step FOREIGN KEY (recipe_step_id) REFERENCES recipe_steps(id) ON DELETE CASCADE
);