CREATE TABLE food_nutrition_dataset
(
    id BIGINT PRIMARY KEY,

    food_name_vi VARCHAR NOT NULL,
    food_name_en VARCHAR,

    energy DOUBLE PRECISION,
    protein DOUBLE PRECISION,
    fat DOUBLE PRECISION,
    carb DOUBLE PRECISION,
    fiber DOUBLE PRECISION,
    calcium DOUBLE PRECISION,
    sodium DOUBLE PRECISION
);

CREATE TABLE ingredient_nutrition
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    updated_by  VARCHAR(255)                            NOT NULL,
    is_deleted  BOOLEAN                                 NOT NULL,

    ingredient_id                                       BIGINT NOT NULL UNIQUE,
    source_food_id                                      BIGINT,
    calories                                            DOUBLE PRECISION,
    protein                                             DOUBLE PRECISION,
    fat                                                 DOUBLE PRECISION,
    carb                                                DOUBLE PRECISION,
    fiber                                               DOUBLE PRECISION,
    calcium                                             DOUBLE PRECISION,
    sodium                                              DOUBLE PRECISION,
    CONSTRAINT fk_ingredient_nutrition FOREIGN KEY (ingredient_id) REFERENCES ingredients(id),
    CONSTRAINT fk_source_food FOREIGN KEY (source_food_id) REFERENCES food_nutrition_dataset(id)
);

CREATE TABLE recipe_nutrition
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    updated_by  VARCHAR(255)                            NOT NULL,
    is_deleted  BOOLEAN                                 NOT NULL,

    recipe_id   BIGINT                                  NOT NULL,
    total_calories                                      DOUBLE PRECISION,
    total_protein                                       DOUBLE PRECISION,
    total_fat                                           DOUBLE PRECISION,
    total_carb                                          DOUBLE PRECISION,
    total_fiber                                         DOUBLE PRECISION,
    total_calcium                                       DOUBLE PRECISION,
    total_sodium                                        DOUBLE PRECISION,
    health_score                                        DOUBLE PRECISION,
    CONSTRAINT fk_recipe_nutrition
        FOREIGN KEY (recipe_id) REFERENCES recipes(id)
);

CREATE TABLE recipe_ingredient_nutrition
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    updated_by  VARCHAR(255)                            NOT NULL,

    recipe_id                                           BIGINT NOT NULL,
    ingredient_id                                       BIGINT NOT NULL,

    quantity                                            DOUBLE PRECISION,

    calories                                            DOUBLE PRECISION,
    protein                                             DOUBLE PRECISION,
    fat                                                 DOUBLE PRECISION,
    carb                                                DOUBLE PRECISION,
    fiber                                               DOUBLE PRECISION,
    calcium                                             DOUBLE PRECISION,
    sodium                                              DOUBLE PRECISION,

    CONSTRAINT fk_rin_recipe
        FOREIGN KEY (recipe_id) REFERENCES recipes(id),
    CONSTRAINT fk_rin_ingredient
        FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
);

CREATE TABLE recipe_nutrition_analysis (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    updated_by  VARCHAR(255)                            NOT NULL,
    recipe_id                                           BIGINT NOT NULL,
    summary                                             TEXT,
    health_level                                        VARCHAR(20),
    recommendation                                      TEXT,

    CONSTRAINT fk_recipe_analysis
       FOREIGN KEY (recipe_id) REFERENCES recipes(id)
);
