CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    updated_by  VARCHAR(255)                            NOT NULL,
    is_deleted  BOOLEAN                                 NOT NULL,
    icon_url    VARCHAR,
    description VARCHAR,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE ingredients
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    updated_by  VARCHAR(255)                            NOT NULL,
    is_deleted  BOOLEAN                                 NOT NULL,
    name        VARCHAR                                 NOT NULL,
    description VARCHAR,
    image       VARCHAR,
    CONSTRAINT pk_ingredients PRIMARY KEY (id)
);

CREATE TABLE recipe_category
(
    category_id BIGINT NOT NULL,
    recipe_id   BIGINT NOT NULL
);

CREATE TABLE recipe_ingredients
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by    VARCHAR(255)                            NOT NULL,
    updated_by    VARCHAR(255)                            NOT NULL,
    is_deleted    BOOLEAN                                 NOT NULL,
    recipe_id     BIGINT                                  NOT NULL,
    ingredient_id BIGINT                                  NOT NULL,
    quantity      DOUBLE PRECISION,
    unit          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_recipe_ingredients PRIMARY KEY (id)
);

CREATE TABLE recipe_steps
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    updated_by  VARCHAR(255)                            NOT NULL,
    is_deleted  BOOLEAN                                 NOT NULL,
    recipe_id   BIGINT                                  NOT NULL,
    step_number INTEGER                                 NOT NULL,
    instruction VARCHAR,
    step_time   INTEGER,
    CONSTRAINT pk_recipe_steps PRIMARY KEY (id)
);

CREATE TABLE recipe_step_images (
    recipe_step_id BIGINT NOT NULL,
    image_url VARCHAR NOT NULL,
    CONSTRAINT fk_recipe_step_images_recipe_step_id
        FOREIGN KEY (recipe_step_id)
            REFERENCES recipe_steps(id)
            ON DELETE CASCADE
);

CREATE TABLE recipe_step_videos (
    recipe_step_id BIGINT NOT NULL,
    video_url VARCHAR NOT NULL,
    CONSTRAINT fk_recipe_step_videos_recipe_step_id
        FOREIGN KEY (recipe_step_id)
            REFERENCES recipe_steps(id)
            ON DELETE CASCADE
);

CREATE TABLE recipes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    updated_by  VARCHAR(255)                            NOT NULL,
    is_deleted  BOOLEAN                                 NOT NULL,
    author_id   BIGINT,
    title       VARCHAR                            NOT NULL,
    description VARCHAR,
    region      VARCHAR,
    image_url   VARCHAR,
    video_url   VARCHAR,
    prep_time   INTEGER,
    cook_time   INTEGER,
    difficulty  VARCHAR(7),
    CONSTRAINT pk_recipes PRIMARY KEY (id)
);

ALTER TABLE recipe_ingredients
    ADD CONSTRAINT FK_RECIPE_INGREDIENTS_ON_INGREDIENT FOREIGN KEY (ingredient_id) REFERENCES ingredients (id);

ALTER TABLE recipe_ingredients
    ADD CONSTRAINT FK_RECIPE_INGREDIENTS_ON_RECIPE FOREIGN KEY (recipe_id) REFERENCES recipes (id);

ALTER TABLE recipe_steps
    ADD CONSTRAINT FK_RECIPE_STEPS_ON_RECIPE FOREIGN KEY (recipe_id) REFERENCES recipes (id);

-- ALTER TABLE shopping_list
--     ADD CONSTRAINT FK_SHOPPING_LIST_ON_RECIPE FOREIGN KEY (recipe_id) REFERENCES recipes (id);

ALTER TABLE recipe_category
    ADD CONSTRAINT fk_reccat_on_category FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE recipe_category
    ADD CONSTRAINT fk_reccat_on_recipe FOREIGN KEY (recipe_id) REFERENCES recipes (id);