-- ================================
-- TABLE: notifications
-- ================================
CREATE TABLE notifications
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    is_deleted      BOOLEAN                                 NOT NULL,

    title           VARCHAR(255)                            NOT NULL,
    body            TEXT,
    path            VARCHAR(255),
    avatar_url      VARCHAR(255),
    post_image_url  VARCHAR(255),
    type            VARCHAR(50)                             NOT NULL,

    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

-- ================================
-- TABLE: notifications_recipient
-- ================================
CREATE TABLE notifications_recipient
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    is_deleted      BOOLEAN                                 NOT NULL,

    user_id          BIGINT,
    notification_id  BIGINT                                   NOT NULL,
    is_read          BOOLEAN                                  NOT NULL DEFAULT FALSE,
    read_at          TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_notifications_recipient PRIMARY KEY (id),
    CONSTRAINT fk_notifications_recipient_notification FOREIGN KEY (notification_id)
        REFERENCES notifications (id) ON DELETE CASCADE
);

-- ================================
-- TABLE: notifications_setting
-- ================================
CREATE TABLE notifications_setting
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    is_deleted      BOOLEAN                                 NOT NULL,

    user_id         BIGINT                                   NOT NULL,
    type            VARCHAR(50),
    enabled         BOOLEAN                                  NOT NULL,

    CONSTRAINT pk_notifications_setting PRIMARY KEY (id)
);

CREATE TABLE user_fcm_tokens
(
    user_id     BIGINT PRIMARY KEY,
    fcm_token   character varying(500)                NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    created_by  character varying(255)                NOT NULL,
    updated_by  character varying(255)                NOT NULL,
    is_deleted  BOOLEAN DEFAULT FALSE
);