CREATE TABLE comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by VARCHAR(255)                            NOT NULL,
    updated_by VARCHAR(255)                            NOT NULL,
    is_deleted BOOLEAN                                 NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    parent_id  BIGINT,
    content    VARCHAR(255)                            NOT NULL,
    post_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE comment_reaction
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment_id    BIGINT                                  NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    reaction_type VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comment_reaction PRIMARY KEY (id)
);

CREATE TABLE comment_reaction_count
(
    comment_id    BIGINT       NOT NULL,
    reaction_type VARCHAR(255) NOT NULL,
    count         BIGINT       NOT NULL,
    CONSTRAINT pk_comment_reaction_count PRIMARY KEY (comment_id, reaction_type)
);

CREATE TABLE post
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by VARCHAR(255)                            NOT NULL,
    updated_by VARCHAR(255)                            NOT NULL,
    is_deleted BOOLEAN                                 NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    recipe_id  BIGINT,
    title      VARCHAR(255),
    content    VARCHAR(255),
    image_url  VARCHAR(255),
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE post_reaction
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id       BIGINT                                  NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    reaction_type VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_post_reaction PRIMARY KEY (id)
);

CREATE TABLE post_reaction_count
(
    comment_id    BIGINT       NOT NULL,
    reaction_type VARCHAR(255) NOT NULL,
    count         BIGINT       NOT NULL,
    CONSTRAINT pk_post_reaction_count PRIMARY KEY (comment_id, reaction_type)
);

CREATE TABLE share
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id    BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    platform   VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_share PRIMARY KEY (id)
);

-- =============================
-- Bảng collection
-- =============================
CREATE TABLE collection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    updated_by VARCHAR(255) NOT NULL DEFAULT 'system',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    cover_image_url VARCHAR(255)
);

-- =============================
-- Bảng collection_post (bảng trung gian)
-- =============================
CREATE TABLE collection_post (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     collection_id BIGINT NOT NULL,
     post_id BIGINT NOT NULL,
     created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
     CONSTRAINT fk_collection_post_collection FOREIGN KEY (collection_id) REFERENCES collection (id) ON DELETE CASCADE,
     CONSTRAINT fk_collection_post_post FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE
);


ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_PARENT FOREIGN KEY (parent_id) REFERENCES comment (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE comment_reaction_count
    ADD CONSTRAINT FK_COMMENT_REACTION_COUNT_ON_COMMENT FOREIGN KEY (comment_id) REFERENCES comment (id);

ALTER TABLE comment_reaction
    ADD CONSTRAINT FK_COMMENT_REACTION_ON_COMMENT FOREIGN KEY (comment_id) REFERENCES comment (id);

ALTER TABLE post_reaction_count
    ADD CONSTRAINT FK_POST_REACTION_COUNT_ON_COMMENT FOREIGN KEY (comment_id) REFERENCES post (id);

ALTER TABLE post_reaction
    ADD CONSTRAINT FK_POST_REACTION_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE share
    ADD CONSTRAINT FK_SHARE_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);