CREATE TABLE chatbot_message
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    is_deleted      BOOLEAN                                 NOT NULL,

    user_id         BIGINT                                  NOT NULL,
    role            VARCHAR(20)                             NOT NULL,
    message         TEXT,
    image_url       VARCHAR(255),

    data            JSONB,
    meta            JSONB,
    chat_tool       VARCHAR(100),

    token_usage     INTEGER,

    CONSTRAINT pk_chat_message PRIMARY KEY (id)
);

CREATE TABLE post_chroma_embedding (
    post_id BIGINT PRIMARY KEY,
    chroma_embedding_id VARCHAR(255) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_chatbot_message_user_role_tool_deleted_created
ON chatbot_message (
user_id,
role,
chat_tool,
is_deleted,
created_at DESC
);