CREATE TABLE diamond_packages
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by     VARCHAR(255)                            NOT NULL,
    updated_by     VARCHAR(255)                            NOT NULL,
    is_deleted     BOOLEAN                                 NOT NULL,
    diamond_amount BIGINT                                  NOT NULL,
    bonus_diamond  BIGINT                                           DEFAULT 0,
    price          DECIMAL                                 NOT NULL,
    currency       VARCHAR(10)                             NOT NULL DEFAULT 'VND',
    is_active      BOOLEAN                                          DEFAULT TRUE,
    CONSTRAINT pk_diamond_packages PRIMARY KEY (id)
);

CREATE TABLE transaction(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    is_deleted      BOOLEAN                                 NOT NULL,

    user_id         BIGINT                                  NOT NULL,

    diamond_package_id      BIGINT                          NOT NULL,

    provider        VARCHAR(50)                             NOT NULL,
    status          VARCHAR(30)                             NOT NULL,

    payment_url     TEXT,
    CONSTRAINT pk_transaction PRIMARY KEY (id),
    CONSTRAINT fk_transaction_diamond_packages
        FOREIGN KEY (diamond_package_id) REFERENCES diamond_packages(id) ON DELETE CASCADE
);

CREATE TABLE user_wallets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id         BIGINT NOT NULL UNIQUE,
    balance_diamond BIGINT NOT NULL DEFAULT 0,
    total_topup     BIGINT NOT NULL DEFAULT 0,
    total_spent     BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE wallet_histories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by      VARCHAR(255) NOT NULL,
    updated_by      VARCHAR(255) NOT NULL,
    is_deleted      BOOLEAN NOT NULL,
    user_id         BIGINT NOT NULL,
    transaction_id  BIGINT,
    type            VARCHAR(50) NOT NULL,
    amount          BIGINT NOT NULL,
    balance_before  BIGINT NOT NULL,
    balance_after   BIGINT NOT NULL,
    CONSTRAINT fk_wallet_history_transaction
      FOREIGN KEY (transaction_id) REFERENCES transaction(id) ON DELETE SET NULL
);

INSERT INTO diamond_packages(created_at,updated_at,created_by,updated_by,is_deleted,diamond_amount,bonus_diamond,price,currency,is_active)
VALUES
    -- Small packages
    (NOW(), NOW(), 'system', 'system', false, 10,   0,   10000,   'VND', true),
    (NOW(), NOW(), 'system', 'system', false, 20,   2,   20000,   'VND', true),
    (NOW(), NOW(), 'system', 'system', false, 50,   5,   50000,   'VND', true),

-- Medium packages
    (NOW(), NOW(), 'system', 'system', false, 100,  15,  99000,   'VND', true),
    (NOW(), NOW(), 'system', 'system', false, 200,  40,  199000,  'VND', true),
    (NOW(), NOW(), 'system', 'system', false, 500,  120, 499000,  'VND', true),

-- Large packages
    (NOW(), NOW(), 'system', 'system', false, 1000, 300, 999000,  'VND', true),
    (NOW(), NOW(), 'system', 'system', false, 2000, 700, 1999000, 'VND', true);

INSERT INTO user_wallets(created_at, updated_at, user_id, balance_diamond, total_topup, total_spent)
VALUES
    (NOW(), NOW(), 1, 0 ,0 ,0),
    (NOW(), NOW(), 2, 0 ,0 ,0),
    (NOW(), NOW(), 3, 0 ,0 ,0),
    (NOW(), NOW(), 4, 0 ,0 ,0),
    (NOW(), NOW(), 5, 0 ,0 ,0),
    (NOW(), NOW(), 6, 0 ,0 ,0),
    (NOW(), NOW(), 7, 0 ,0 ,0),
    (NOW(), NOW(), 8, 0 ,0 ,0),
    (NOW(), NOW(), 9, 0 ,0 ,0),
    (NOW(), NOW(), 10, 0 ,0 ,0),
    (NOW(), NOW(), 11, 0 ,0 ,0),
    (NOW(), NOW(), 12, 0 ,0 ,0),
    (NOW(), NOW(), 13, 0 ,0 ,0),
    (NOW(), NOW(), 14, 0 ,0 ,0),
    (NOW(), NOW(), 15, 0 ,0 ,0),
    (NOW(), NOW(), 16, 0 ,0 ,0),
    (NOW(), NOW(), 17, 0 ,0 ,0),
    (NOW(), NOW(), 18, 0 ,0 ,0),
    (NOW(), NOW(), 19, 0 ,0 ,0),
    (NOW(), NOW(), 20, 0 ,0 ,0),
    (NOW(), NOW(), 23, 0 ,0 ,0),
    (NOW(), NOW(), 24, 0 ,0 ,0),
    (NOW(), NOW(), 25, 0 ,0 ,0),
    (NOW(), NOW(), 26, 0 ,0 ,0);