CREATE TABLE story (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    created_by       VARCHAR(255)                            NOT NULL,
    updated_by       VARCHAR(255)                            NOT NULL,
    is_deleted       BOOLEAN DEFAULT FALSE                   NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    type             VARCHAR(50)                             NOT NULL,
    content_url      TEXT                                    NOT NULL,
    expired_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_story PRIMARY KEY (id)
);

CREATE TABLE story_view (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    story_id         BIGINT NOT NULL,
    user_id          BIGINT NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_story_view FOREIGN KEY (story_id) REFERENCES story (id) ON DELETE CASCADE
);

CREATE TABLE story_comment (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    created_by       VARCHAR(255)                            NOT NULL,
    updated_by       VARCHAR(255)                            NOT NULL,
    is_deleted       BOOLEAN                                 NOT NULL DEFAULT FALSE,
    story_id         BIGINT                                  NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    parent_id        BIGINT                                  ,
    message          TEXT                                    NOT NULL,

    CONSTRAINT pk_story_comment PRIMARY KEY (id),
    CONSTRAINT fk_story_comment_on_story
       FOREIGN KEY (story_id) REFERENCES story(id) ON DELETE CASCADE,
    CONSTRAINT fk_story_comment_parent
        FOREIGN KEY (parent_id) REFERENCES story_comment(id) ON DELETE CASCADE
);

CREATE TABLE story_reaction (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    story_id         BIGINT NOT NULL,
    user_id          BIGINT NOT NULL,
    reaction_type    VARCHAR(50) NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_story_reaction FOREIGN KEY (story_id) REFERENCES story (id) ON DELETE CASCADE
);

CREATE TABLE story_reaction_count (
    story_id          BIGINT NOT NULL,
    reaction_type     VARCHAR(50) NOT NULL,
    count             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_story_reaction_count PRIMARY KEY (story_id, reaction_type)
);

CREATE TABLE story_setting (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           BIGINT NOT NULL,
    mode              VARCHAR(50) NOT NULL,
    CONSTRAINT pk_story_setting PRIMARY KEY (id)
);

CREATE TABLE story_setting_whitelist (
    setting_id        BIGINT NOT NULL,
    allowed_user_id   BIGINT NOT NULL,
    CONSTRAINT fk_story_setting_whitelist FOREIGN KEY (setting_id)
     REFERENCES story_setting(id) ON DELETE CASCADE
);

CREATE TABLE story_setting_blacklist (
    setting_id        BIGINT NOT NULL,
    blocked_user_id   BIGINT NOT NULL,
    CONSTRAINT fk_story_setting_blacklist FOREIGN KEY (setting_id)
     REFERENCES story_setting(id) ON DELETE CASCADE
);

-- Tạo bảng story_collection
CREATE TABLE story_collection (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    created_by  VARCHAR(255) NOT NULL,
    updated_by  VARCHAR(255) NOT NULL,
    is_deleted  BOOLEAN DEFAULT FALSE NOT NULL,
    user_id     BIGINT NOT NULL,
    name        VARCHAR(255) NOT NULL,
    image_url TEXT,
    description TEXT,
    CONSTRAINT pk_story_collection PRIMARY KEY (id)
);

-- Tạo bảng story_collection_item
CREATE TABLE story_collection_item (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    collection_id BIGINT NOT NULL,
    story_id      BIGINT NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_story_collection_item PRIMARY KEY (id),
    CONSTRAINT fk_story_collection_item_collection
       FOREIGN KEY (collection_id) REFERENCES story_collection(id) ON DELETE CASCADE,
    CONSTRAINT fk_story_collection_item_story
       FOREIGN KEY (story_id) REFERENCES story(id) ON DELETE CASCADE
);



INSERT INTO story (created_at, updated_at, created_by, updated_by, is_deleted,
                   user_id, type, content_url, expired_at)
VALUES
    (NOW(), NOW(), 'system', 'system', false, 1, 'IMAGE',
     'https://didongviet.vn/dchannel/wp-content/uploads/2023/08/galaxy-hinh-nen-iphone-doc-dep-didongviet@2x-576x1024.jpg', NOW() + INTERVAL '24 HOURS'),

    (NOW(), NOW(), 'system', 'system', false, 2, 'IMAGE',
     'https://cellphones.com.vn/sforum/wp-content/uploads/2021/02/fantasy-landscape-iPhone-wallpaper-idownloadblog-IEDITWALLS20.11.25104242-@aronvisuals-728x1536-1.jpg', NOW() + INTERVAL '24 HOURS'),

    (NOW(), NOW(), 'system', 'system', false, 3, 'IMAGE',
     'https://cdn2.fptshop.com.vn/unsafe/hinh_nen_iphone_doc_dep_22_a3d94e7220.jpg', NOW() + INTERVAL '24 HOURS');

INSERT INTO story_view (story_id, user_id, created_at)
VALUES
    (1, 2, NOW()),
    (1, 3, NOW()),
    (2, 1, NOW()),
    (2, 4, NOW()),
    (3, 5, NOW());

INSERT INTO story_comment (created_at, updated_at, created_by, updated_by, is_deleted,
                           story_id, user_id, message, parent_id)
VALUES
    (NOW(), NOW(), 'system', 'system', false, 1, 2, 'Story đẹp quá!',NULL),
    (NOW(), NOW(), 'system', 'system', false, 1, 3, 'Hình chất lượng ghê',NULL),
    (NOW(), NOW(), 'system', 'system', false, 2, 1, 'Video xịn thật',NULL),
    (NOW(), NOW(), 'system', 'system', false, 3, 4, 'View đẹp quá!',NULL);

-- Thêm cho comment reply cấp 2
INSERT INTO story_comment (
    created_at, updated_at, created_by, updated_by, is_deleted,
    story_id, user_id, message, parent_id
) VALUES
      (NOW(), NOW(), 'system', 'system', false, 1, 1, 'Đồng ý, đẹp thật!', 1),
      (NOW(), NOW(), 'system', 'system', false, 1, 2, 'Ảnh này ở đâu thế?', 1),

      (NOW(), NOW(), 'system', 'system', false, 1, 3, 'Chuẩn, ảnh chất lượng!', 2),

      (NOW(), NOW(), 'system', 'system', false, 2, 23, 'Máy gì quay mà nét vậy?', 3),

      (NOW(), NOW(), 'system', 'system', false, 3, 4, 'View chill quá!', 4);

INSERT INTO story_reaction (story_id, user_id, reaction_type, created_at)
VALUES
    (1, 2, 'LIKE', NOW()),
    (1, 3, 'LOVE', NOW()),
    (2, 1, 'LIKE', NOW()),
    (3, 4, 'WOW', NOW());

INSERT INTO story_reaction_count (story_id, reaction_type, count)
VALUES
    (1, 'LIKE', 1),
    (1, 'LOVE', 1),
    (2, 'LIKE', 1),
    (3, 'WOW', 1);

INSERT INTO story_setting (user_id, mode)
VALUES
    (1, 'CUSTOM_INCLUDE'),
    (2, 'CUSTOM_INCLUDE'),
    (3, 'CUSTOM_INCLUDE'),
    (4, 'BLACKLIST'),
    (23, 'FOLLOWING_ONLY');

INSERT INTO story_setting_whitelist (setting_id, allowed_user_id)
VALUES
    (3, 1),
    (3, 2),
    (5, 1),
    (5, 2),
    (5, 3),
    (1, 23),
    (2, 23),
    (3, 23);

INSERT INTO story_setting_blacklist (setting_id, blocked_user_id)
VALUES
    (4, 6),
    (4, 7),
    (4, 8);


-- Thêm dữ liệu mẫu cho story_collection
INSERT INTO story_collection (created_at, updated_at, created_by, updated_by, is_deleted, user_id, name, image_url,description)
VALUES
    (NOW(), NOW(), 'system', 'system', false, 1, 'Summer Vacation', 'https://cellphones.com.vn/sforum/wp-content/uploads/2023/12/hinh-nen-vu-tru-1.jpg','Collection of summer vacation stories'),
    (NOW(), NOW(), 'system', 'system', false, 2, 'Work Highlights', 'https://didongviet.vn/dchannel/wp-content/uploads/2023/08/galaxy-hinh-nen-iphone-doc-dep-didongviet@2x-576x1024.jpg','Stories from work projects'),
    (NOW(), NOW(), 'system', 'system', false, 3, 'Family Moments', 'https://i.pinimg.com/474x/30/f4/94/30f494940bc3cdf1d36f845764271452.jpg','Personal family memories');

-- Thêm dữ liệu mẫu cho story_collection_item
INSERT INTO story_collection_item (collection_id, story_id, created_at)
VALUES
    (1, 1, NOW()),
    (1, 2, NOW()),
    (2, 3, NOW()),
    (3, 1, NOW()),
    (3, 3, NOW());