CREATE TABLE diamond_packages {
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    is_deleted      BOOLEAN                                 NOT NULL,
    diamond_amount  BIGINT                                  NOT NULL,
    bonus_diamond   BIGINT                                  DEFAULT 0,
    price           DECIMAL                                 NOT NULL,
    currency        VARCHAR(10)                             NOT NULL DEFAULT 'VND',
    is_active       BOOLEAN                                 DEFAULT TRUE,
}

CREATE TABLE transaction(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    is_deleted      BOOLEAN                                 NOT NULL,

    user_id         BIGINT                                  NOT NULL,

    diamond_package_id      BIGINT                          NOT NULL,

    provider        VARCHAR(50)                             NOT NULL,
    status          VARCHAR(30)                             NOT NULL,

    payment_url     TEXT,
    CONSTRAINT fk_transaction_diamond_packages
        FOREIGN KEY (diamond_package_id) REFERENCES diamond_packages(id) ON DELETE CASCADE
);