-- REPORT POST
CREATE TABLE report_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    updated_by VARCHAR(255) NOT NULL DEFAULT 'system',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    reporter_id BIGINT NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    post_id BIGINT NOT NULL,
    CONSTRAINT pk_report_post PRIMARY KEY (id)
);

-- REPORT COMMENT
CREATE TABLE report_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    updated_by VARCHAR(255) NOT NULL DEFAULT 'system',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    reporter_id BIGINT NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    comment_id BIGINT NOT NULL,
    CONSTRAINT pk_report_comment PRIMARY KEY (id)
);

-- REPORT STORY
CREATE TABLE report_story (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    updated_by VARCHAR(255) NOT NULL DEFAULT 'system',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    reporter_id BIGINT NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    story_id BIGINT NOT NULL,
    CONSTRAINT pk_report_story PRIMARY KEY (id)
);

-- REPORT STORY
INSERT INTO report_story (reporter_id, target_type, reason, status, story_id)
VALUES
    (2, 'STORY',   'Hình ảnh không phù hợp', 'PENDING', 1),
    (3, 'STORY',   'Video spam quảng cáo', 'PENDING', 2),
    (4, 'STORY',   'Story có nội dung thù ghét', 'PENDING', 3);

-- REPORT COMMENT
INSERT INTO report_comment (reporter_id, target_type, reason, status, comment_id)
VALUES
    (5, 'COMMENT', 'Bình luận không phù hợp', 'PENDING', 1),
    (6, 'COMMENT', 'Bình luận spam quảng cáo', 'PENDING', 3);

-- REPORT POST
INSERT INTO report_post (reporter_id, target_type, reason, status, post_id)
VALUES
    (7, 'POST', 'Bài viết có nội dung thù ghét', 'PENDING', 1),
    (8, 'POST', 'Bài viết spam quảng cáo', 'PENDING', 2);