CREATE TABLE chat_message
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    is_deleted      BOOLEAN                                 NOT NULL,

    user_id         BIGINT                                  NOT NULL,
    role            VARCHAR(20)                             NOT NULL,
    input_text      TEXT,
    input_image_url VARCHAR(255),

    output_json     JSONB,
    chat_tool       VARCHAR(100),

    token_usage     INTEGER,

    CONSTRAINT pk_chat_message PRIMARY KEY (id)
);

CREATE TABLE post_chroma_embedding (
    post_id BIGINT PRIMARY KEY,
    chroma_embedding_id VARCHAR(255) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);