CREATE TABLE report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    updated_by VARCHAR(255) NOT NULL DEFAULT 'system',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    reporter_id BIGINT NOT NULL,

    target_type VARCHAR(50) NOT NULL,
    target_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    CONSTRAINT pk_report PRIMARY KEY (id)
);

INSERT INTO report (created_at, updated_at, created_by, updated_by, is_deleted,
                    reporter_id, target_type, target_id, reason, status)
VALUES
    -- Report story
    (NOW(), NOW(), 'system', 'system', FALSE, 2, 'STORY', 1,  'Hình ảnh không phù hợp', 'PENDING'),
    (NOW(), NOW(), 'system', 'system', FALSE, 3, 'STORY', 2,  'Video spam quảng cáo', 'PENDING'),
    (NOW(), NOW(), 'system', 'system', FALSE, 4, 'STORY', 3,  'Story có nội dung thù ghét', 'PENDING'),

    -- Report story comment
    (NOW(), NOW(), 'system', 'system', FALSE, 5, 'COMMENT', 1,  'Comment không phù hợp', 'PENDING'),
    (NOW(), NOW(), 'system', 'system', FALSE, 6, 'COMMENT', 3,  'Comment spam quảng cáo', 'PENDING'),

    -- Report post (giả sử post id = 1, 2)
    (NOW(), NOW(), 'system', 'system', FALSE, 7, 'POST', 1,  'Bài viết có nội dung thù ghét', 'PENDING'),
    (NOW(), NOW(), 'system', 'system', FALSE, 8, 'POST', 2,  'Bài viết spam quảng cáo', 'PENDING');