CREATE TABLE live_gift_items(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by     VARCHAR(255)                            NOT NULL,
    updated_by     VARCHAR(255)                            NOT NULL,
    is_deleted     BOOLEAN                                 NOT NULL,
    name            VARCHAR(100) NOT NULL,
    image_url       TEXT NOT NULL,
    animation_url   TEXT,
    diamond_cost    BIGINT NOT NULL,
    host_share_percent INT NOT NULL DEFAULT 70,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE livestream_gift_logs(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by     VARCHAR(255)                            NOT NULL,
    updated_by     VARCHAR(255)                            NOT NULL,
    is_deleted     BOOLEAN                                 NOT NULL,
    sender_id             BIGINT NOT NULL,
    receiver_id           BIGINT NOT NULL,
    livestream_id         BIGINT NOT NULL,
    live_gift_item_id          BIGINT NOT NULL,
    quantity              INT NOT NULL DEFAULT 1,
    total_diamond_spent   BIGINT NOT NULL,
    host_diamond_received BIGINT NOT NULL,
    CONSTRAINT fk_livestream_gift_logs
        FOREIGN KEY (livestream_id) REFERENCES live_streams(id) ON DELETE CASCADE,
    CONSTRAINT fk_live_gift_item
        FOREIGN KEY (live_gift_item_id) REFERENCES live_gift_items(id) ON DELETE CASCADE
);

CREATE INDEX idx_gift_log_sender      ON livestream_gift_logs(sender_id);
CREATE INDEX idx_gift_log_receiver    ON livestream_gift_logs(receiver_id);
CREATE INDEX idx_gift_log_livestream  ON livestream_gift_logs(livestream_id);
CREATE INDEX idx_gift_log_created     ON livestream_gift_logs(created_at);

INSERT INTO live_gift_items(created_at,updated_at,created_by,updated_by,is_deleted,name, image_url, animation_url, diamond_cost, host_share_percent, is_active)
VALUES
    (NOW(), NOW(), 'system', 'system', false,'Hoa hồng',    'https://res.cloudinary.com/dlkvdusla/image/upload/v1779802840/red-rose_jfwrdt.png',       'https://lottie.host/5984196f-02c7-4ff4-ab2c-fd119f272bc8/mMF3ht7arW.json',       10,   70, true),
    (NOW(), NOW(), 'system', 'system', false,'Cà phê',    'https://res.cloudinary.com/dlkvdusla/image/upload/v1779802972/coffee_vtwzmj.png',   'https://lottie.host/8eaf3389-fd43-4ff3-a006-9a8ec1874f2c/XSP4JR96b6.json',   50,   70, true),
    (NOW(), NOW(), 'system', 'system', false,'Bánh kem',     'https://res.cloudinary.com/dlkvdusla/image/upload/v1779803259/cake_tabqeo.png',   'https://lottie.host/d42afa7a-83bf-45ee-a6ca-ccf3d4cb06c3/ipQiI3D5CX.json',   500,  75, true),
    (NOW(), NOW(), 'system', 'system', false,'Sao Michelin',   'https://res.cloudinary.com/dlkvdusla/image/upload/v1779803416/star_ztbzrw.png',      'https://lottie.host/ee58be10-e33e-41f5-8626-d4e4f877e14f/CSdDiIpvTE.json',      5000, 80, true);