CREATE TABLE story (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    created_by       VARCHAR(255)                            NOT NULL,
    updated_by       VARCHAR(255)                            NOT NULL,
    is_deleted       BOOLEAN DEFAULT FALSE                   NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    type             VARCHAR(50)                             NOT NULL,
    content_url      TEXT                                    NOT NULL,
    expired_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_story PRIMARY KEY (id)
);

CREATE TABLE story_view (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    story_id         BIGINT NOT NULL,
    user_id          BIGINT NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_story_view FOREIGN KEY (story_id) REFERENCES story (id) ON DELETE CASCADE
);

CREATE TABLE story_comment (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    created_by       VARCHAR(255)                            NOT NULL,
    updated_by       VARCHAR(255)                            NOT NULL,
    is_deleted       BOOLEAN                                 NOT NULL DEFAULT FALSE,
    story_id         BIGINT                                  NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    message          TEXT                                    NOT NULL,

    CONSTRAINT pk_story_comment PRIMARY KEY (id),
    CONSTRAINT fk_story_comment_on_story
       FOREIGN KEY (story_id) REFERENCES story(id) ON DELETE CASCADE
);

CREATE TABLE story_reaction (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    story_id         BIGINT NOT NULL,
    user_id          BIGINT NOT NULL,
    reaction_type    VARCHAR(50) NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_story_reaction FOREIGN KEY (story_id) REFERENCES story (id) ON DELETE CASCADE
);

CREATE TABLE story_reaction_count (
    story_id          BIGINT NOT NULL,
    reaction_type     VARCHAR(50) NOT NULL,
    count             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_story_reaction_count PRIMARY KEY (story_id, reaction_type)
);

INSERT INTO story (created_at, updated_at, created_by, updated_by, is_deleted,
                   user_id, type, content_url, expired_at)
VALUES
    (NOW(), NOW(), 'system', 'system', false, 1, 'IMAGE',
     'https://example.com/story1.jpg', NOW() + INTERVAL '24 HOURS'),

    (NOW(), NOW(), 'system', 'system', false, 2, 'VIDEO',
     'https://example.com/story2.mp4', NOW() + INTERVAL '24 HOURS'),

    (NOW(), NOW(), 'system', 'system', false, 3, 'IMAGE',
     'https://example.com/story3.jpg', NOW() + INTERVAL '24 HOURS');

INSERT INTO story_view (story_id, user_id, created_at)
VALUES
    (1, 2, NOW()),
    (1, 3, NOW()),
    (2, 1, NOW()),
    (2, 4, NOW()),
    (3, 5, NOW());

INSERT INTO story_comment (created_at, updated_at, created_by, updated_by, is_deleted,
                           story_id, user_id, message)
VALUES
    (NOW(), NOW(), 'system', 'system', false, 1, 2, 'Story đẹp quá!'),
    (NOW(), NOW(), 'system', 'system', false, 1, 3, 'Hình chất lượng ghê'),
    (NOW(), NOW(), 'system', 'system', false, 2, 1, 'Video xịn thật'),
    (NOW(), NOW(), 'system', 'system', false, 3, 4, 'View đẹp quá!');

INSERT INTO story_reaction (story_id, user_id, reaction_type, created_at)
VALUES
    (1, 2, 'LIKE', NOW()),
    (1, 3, 'LOVE', NOW()),
    (2, 1, 'LIKE', NOW()),
    (3, 4, 'WOW', NOW());

INSERT INTO story_reaction_count (story_id, reaction_type, count)
VALUES
    (1, 'LIKE', 1),
    (1, 'LOVE', 1),
    (2, 'LIKE', 1),
    (3, 'WOW', 1);