# server discovery
eureka:
  instance:
    hostname: ${env.discovery.eureka.hostname:localhost}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${env.discovery.eureka.client.service-url.defaultZone:http://localhost:8761/eureka}

spring:
  cloud:
    config:
      override-system-properties: false
  main:
    allow-bean-definition-overriding: true

# security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${env.global.jwt.issuer-uri:http://localhost:9098/realms/eefood-realm}
  kafka:
    bootstrap-servers: ${env.global.kafka.bootstrap-servers:localhost:9092}

idp:
  url: ${env.global.idp.url:http://localhost:9098}
  realm: ${env.global.realm:eefood-realm}
  client-id: ${env.global.idp.client-id:client_backend}
  client-secret: ${env.global.idp.client-secret:MCKrWc2Ru5WE1TQodq0EKxliT5xe0wqD}


