spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      server:
        webflux:
          routes:
            - id: keycloak
              uri: http://localhost:9098
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /$\{segment}

            - id: patient-service
              uri: lb://PATIENT-SERVICE
              predicates:
                - Path=/api/v1/patients/**
            - id: dfasfsad
              uri: lb://IAM-SERVICE
              predicates:
                - Path=/api/v1/users/**
#http://localhost:8222/api/v1/users/1
#lb://IAM-SERVICE/api/v1/users/1
#http://localhost:8085/api/v1/users/1
            - id: test-order-service-order
              uri: lb://TEST-ORDER-SERVICE
              predicates:
                - Path=/api/v1/test-order/**

            - id: test-order-service-comments
              uri: lb://TEST-ORDER-SERVICE
              predicates:
                - Path=/api/v1/comments/**

            - id: iam-service-users
              uri: lb://IAM-SERVICE
              predicates:
                - Path=/api/v1/users/**
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: ${env.global.kafka.brokers}
      bindings:
        springCloudBusInput:
          destination: springCloudBus
        springCloudBusOutput:
          destination: springCloudBus
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

server:
  port: 8222

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh       # Cho phép gọi /actuator/refresh để nạp lại cấu hình (dùng với Spring Cloud Config)
          - health        # Cho phép truy cập endpoint /actuator/health để kiểm tra tình trạng ứng dụng
          - info          # Cho phép truy cập /actuator/info để xem thông tin ứng dụng
          - metrics       # Cho phép truy cập /actuator/metrics để xem tất cả metric hiện có
          - prometheus    # Cho phép Prometheus scrape metrics tại /actuator/prometheus

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: gateway-service # Gắn nhãn `application=gateway-service` vào tất cả metric
