server:
  port: 8095
  servlet:
    context-path: /
    session:
      cookie:
        same-site: strict
        http-only: true

livekit:
  api:
    key: ${LIVEKIT_API_KEY:devkey}
    secret: ${LIVEKIT_API_SECRET:secret}
  ws:
    url:  ${LIVEKIT_WS_URL:ws://127.0.0.1:7880}
  http:
    url: ${LIVEKIT_HTTP_URL:http://127.0.0.1:7880}

whisper:
  base-url: ${WHISPER_BASE_URL:http://127.0.0.1:8091}

elasticsearch:
  host: ${ES_HOST:localhost}
  port: ${ES_PORT:9200}
  username: ${ES_USERNAME:elastic}
  password: ${ES_PASSWORD:elastic123}

spring:
  cache:
    type: redis
  data:
    redis:
      host: ${env.global.redis.host:localhost}
      port: ${env.global.redis.port:6379}
  application:
    name: reaction-service
  config:
    import: optional:configserver:${env.global.config-server:http://localhost:8888}

#  kafka
  kafka:
    bootstrap-servers:  ${env.global.kafka.bootstrap-servers:localhost:9092}
    properties:
      schema.registry.url: ${env.global.kafka.schema-registry-url:http://localhost:8086}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true

  datasource:
    url: ${env.reaction.datasource.url:jdbc:postgresql://localhost:5435/reaction_service}
    username: ${env.reaction.datasource.username:postgres}
    password: ${env.reaction.datasource.password:postgres}
    hikari:
      connection-timeout: 5000       # Timeout khi lấy connection (5s)
      validation-timeout: 3000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        envers:
          audit_table_suffix: _aud
          store_data_at_delete: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

management:
  health:
    elasticsearch:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - refresh       # Cho phép gọi /actuator/refresh để nạp lại cấu hình (dùng với Spring Cloud Config)
          - health        # Cho phép truy cập endpoint /actuator/health để kiểm tra tình trạng ứng dụng
          - info          # Cho phép truy cập /actuator/info để xem thông tin ứng dụng
          - metrics       # Cho phép truy cập /actuator/metrics để xem tất cả metric hiện có
          - prometheus    # Cho phép Prometheus scrape metrics tại /actuator/prometheus

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

  observations:
    key-values:
      application: iam-service # Gắn nhãn `application=iam-service` vào tất cả metric

logging:
  charset:
    console: UTF-8
  level:
    root: INFO
    # Log feign chi tiết
    feign: DEBUG
    feign.client: DEBUG

google:
  ai:
    gemini:
      api-key: ${GEMINI_API_KEY}
      model: gemini-2.5-flash
      embedding-model: gemini-embedding-001
      temperature: 0.1
chroma:
  host: localhost
  port: 8010
  collection: my-collection






