version: "3.8"

services:
  discovery-server:
    image: ledinhloc/discovery:latest
    ports:
      - "8761:8761"
    networks:
      - eefood-network

  config-service:
    image: ledinhloc/config-service:latest
    ports:
      - "8888:8888"
    depends_on:
      - discovery-server
    networks:
      - eefood-network

  gateway-service:
    image: ledinhloc/gateway:latest
    ports:
      - "8222:8222"
    depends_on:
      - config-service
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET}
    networks:
      - eefood-network

  iam-service:
    image: ledinhloc/iam-service:latest
    ports:
      - "8085:8085"
    depends_on:
      - config-service
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET}
    networks:
      - eefood-network

  recipe-service:
    image: ledinhloc/recipe-service:latest
    ports:
      - "8100:8100"
    depends_on:
      - config-service
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    networks:
      - eefood-network

  reaction-service:
    image: ledinhloc/reaction-service:latest
    ports:
      - "8095:8095"
    depends_on:
      - config-service
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    networks:
      - eefood-network

  notification-service:
    image: ledinhloc/notification-service:latest
    ports:
      - "8090:8090"
    depends_on:
      - config-service
    environment:
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    volumes:
      - ./firebase/google-service.json:/app/resources/google-service.json
      - ./firebase/serviceAccountKey.json:/app/resources/serviceAccountKey.json
    networks:
      - eefood-network

networks:
  eefood-network:
    driver: bridge
