CREATE TABLE public.user_height
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint                NOT NULL,
    height_cm   numeric(5, 2)         NOT NULL,
    recorded_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT fk_user_height_user FOREIGN KEY (user_id) REFERENCES public.users (id),
    CONSTRAINT chk_user_height_height_positive CHECK (height_cm > 0)
);

CREATE INDEX idx_user_height_user_recorded_at
    ON public.user_height (user_id, recorded_at DESC);

CREATE TABLE public.user_weight
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint                NOT NULL,
    weight_kg   numeric(5, 2)         NOT NULL,
    recorded_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT fk_user_weight_user FOREIGN KEY (user_id) REFERENCES public.users (id),
    CONSTRAINT chk_user_weight_weight_positive CHECK (weight_kg > 0)
);

CREATE INDEX idx_user_weight_user_recorded_at
    ON public.user_weight (user_id, recorded_at DESC);

CREATE TABLE public.user_health_conditions
(
    user_id         bigint NOT NULL,
    condition_name  character varying(255),
    CONSTRAINT fk_user_health_conditions FOREIGN KEY (user_id) REFERENCES public.users (id)
);

ALTER TABLE public.users
    ADD COLUMN activity_level character varying(20);

ALTER TABLE public.users
    ADD CONSTRAINT users_activity_level_check
        CHECK (activity_level IN ('SEDENTARY', 'LIGHT', 'MODERATE', 'ACTIVE'));
