INSERT INTO public.users (created_by,
                          is_deleted,
                          updated_at,
                          updated_by,
                          address,
                          auth_id,
                          avatar_url,
                          background_url,
                          dob,
                          email,
                          gender,
                          provider,
                          role,
                          username)
VALUES ('system', false, now(), 'system', '{"city":"Hà Nội","street":"12 Nguyễn Trãi"}', NULL, NULL, NULL,'2004-05-12',
        'ledinhloc7@gmail.com', 'MALE', 'NORMAL', 'USER', 'Le Dinh Loc'),
       ('system', false, now(), 'system', '{"city":"Hồ Chí Minh","street":"45 Lê Lợi"}', NULL, NULL, NULL,'2004-11-23',
        'akhoa2109@gmail.com', 'MALE', 'NORMAL', 'USER', 'Nguyen Hoang Anh Khoa'),
       ('system', false, now(), 'system', '{"city":"Đà Nẵng","street":"78 Hải Phòng"}', NULL, NULL, NULL,'1998-03-14',
        'minhquan98@gmail.com', 'MALE', 'NORMAL', 'ADMIN', 'Minh Quân'),
       ('system', false, now(), 'system', '{"city":"Huế","street":"21 Hùng Vương"}', NULL, NULL, NULL,'1990-07-30',
        'thuydung90@gmail.com', 'FEMALE', 'NORMAL', 'USER', 'Thúy Dung'),
       ('system', false, now(), 'system', '{"city":"Cần Thơ","street":"5 Nguyễn Văn Linh"}', NULL, NULL, NULL,'1988-12-01',
        'anhkhoa88@gmail.com', 'MALE', 'GOOGLE', 'USER', 'Anh Khoa'),
       ('system', false, now(), 'system', '{"city":"Hải Phòng","street":"33 Điện Biên Phủ"}', NULL, NULL, NULL,'1997-08-18',
        'lanphuong97@gmail.com', 'FEMALE', 'NORMAL', 'USER', 'Lan Phương'),
       ('system', false, now(), 'system', '{"city":"Quảng Ninh","street":"9 Trần Phú"}', NULL, NULL, NULL,'1996-06-10',
        'ductruong96@gmail.com', 'MALE', 'NORMAL', 'USER', 'Đức Trường'),
       ('system', false, now(), 'system', '{"city":"Nam Định","street":"101 Hàng Bông"}', NULL, NULL, NULL,'1991-02-27',
        'hoamai91@gmail.com', 'FEMALE', 'GOOGLE', 'USER', 'Hoa Mai'),
       ('system', false, now(), 'system', '{"city":"Bình Định","street":"25 Lê Duẩn"}', NULL, NULL, NULL,'1994-09-15',
        'hoanganh94@gmail.com', 'FEMALE', 'NORMAL', 'USER', 'Hoàng Anh'),
       ('system', false, now(), 'system', '{"city":"Khánh Hòa","street":"88 Trần Quang Khải"}', NULL, NULL,
        NULL,'1993-04-05', 'tienphat93@gmail.com', 'MALE', 'GOOGLE', 'ADMIN', 'Tiến Phát'),
       ('system', false, now(), 'system', '{"city":"Đắk Lắk","street":"12 Lý Thường Kiệt"}', NULL, NULL, NULL,'1989-10-22',
        'vanlam89@gmail.com', 'MALE', 'NORMAL', 'USER', 'Văn Lâm'),
       ('system', false, now(), 'system', '{"city":"Nghệ An","street":"77 Quang Trung"}', NULL, NULL, NULL,'1995-01-19',
        'lethao95@gmail.com', 'FEMALE', 'NORMAL', 'USER', 'Lệ Thảo'),
       ('system', false, now(), 'system', '{"city":"Thanh Hóa","street":"30 Bà Triệu"}', NULL, NULL, NULL,'1999-06-09',
        'sondinh99@gmail.com', 'MALE', 'GOOGLE', 'USER', 'Sơn Đình'),
       ('system', false, now(), 'system', '{"city":"An Giang","street":"55 Lê Lai"}', NULL, NULL, NULL,'1992-12-31',
        'huongtran92@gmail.com', 'FEMALE', 'NORMAL', 'USER', 'Hương Trần'),
       ('system', false, now(), 'system', '{"city":"Kiên Giang","street":"60 Nguyễn Huệ"}', NULL, NULL, NULL,'1997-03-02',
        'trieuphu97@gmail.com', 'MALE', 'GOOGLE', 'USER', 'Triệu Phú'),
       ('system', false, now(), 'system', '{"city":"Vũng Tàu","street":"101 Võ Thị Sáu"}', NULL, NULL, NULL,'1990-05-25',
        'thuytrang90@gmail.com', 'FEMALE', 'NORMAL', 'USER', 'Thùy Trang'),
       ('system', false, now(), 'system', '{"city":"Hà Nội","street":"14 Láng Hạ"}', NULL, NULL, NULL,'1987-09-09',
        'longnguyen87@gmail.com', 'MALE', 'GOOGLE', 'USER', 'Nguyễn Long'),
       ('system', false, now(), 'system', '{"city":"Hà Nam","street":"27 Trần Hưng Đạo"}', NULL, NULL, NULL,'1998-11-11',
        'minhchau98@gmail.com', 'FEMALE', 'NORMAL', 'ADMIN', 'Minh Châu'),
       ('system', false, now(), 'system', '{"city":"Lâm Đồng","street":"19 Phan Đình Phùng"}', NULL, NULL, NULL,'1996-07-01',
        'duchoang96@gmail.com', 'MALE', 'NORMAL', 'USER', 'Đức Hoàng'),
       ('system', false, now(), 'system', '{"city":"Quảng Nam","street":"22 Lý Tự Trọng"}', NULL, NULL, NULL,'1993-02-20',
        'thuytien93@gmail.com', 'FEMALE', 'GOOGLE', 'USER', 'Thùy Tiên');
