CREATE TABLE public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp(6) without time zone DEFAULT now(),
  created_by character varying(255) NOT NULL,
  is_deleted boolean NOT NULL DEFAULT false,
  updated_at timestamp(6) without time zone DEFAULT now(),
  updated_by character varying(255) NOT NULL,
  address jsonb,
  auth_id character varying(255),
  avatar_url character varying(255),
  dob date,
  email character varying(255) NOT NULL UNIQUE,
  gender character varying(10),
  provider character varying(255) NOT NULL,
  role character varying(20) NOT NULL,
  username character varying(255) NOT NULL,
  CONSTRAINT users_gender_check CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
  CONSTRAINT users_provider_check CHECK (provider IN ('GOOGLE', 'NORMAL')),
  CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE public.otp (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false,
    otp_expired timestamp(6) without time zone NOT NULL,
    otp_num character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT fk_otp_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE public.user_allergies (
   user_id bigint NOT NULL,
   allergy character varying(255),
   CONSTRAINT fk_user_allergies FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE public.user_eating_preferences (
    user_id bigint NOT NULL,
    preference character varying(255),
    CONSTRAINT fk_user_preferences FOREIGN KEY (user_id) REFERENCES public.users(id)
);