name: CI/CD Deploy to VPS

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Danh sách các thư mục con tương ứng với các service
        service: [config-service, discovery, gateway, iam-service, notification-service, reaction-service, recipe-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build JAR for ${{ matrix.service }}
        run: |
          cd services/${{ matrix.service }}
          mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./services/${{ matrix.service }}
          push: true
          tags: ledinhloc/${{ matrix.service }}:latest

  build-and-push-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: ai-service
            context: ./services/ai-service
          - service: subtitle-worker
            context: ./tools/subtitle-worker

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ledinhloc/${{ matrix.service }}:latest

  deploy:
    needs: [build-and-push, build-and-push-python]
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/eefood # Đường dẫn chứa file docker-compose.app.yml trên VPS
            docker compose -f docker-compose.app.yml pull
            docker compose -f docker-compose.app.yml up -d
